apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: mohamedessam1911/fastapi-app:latest  # Replace with your Docker Hub image if pushing remotely
        ports:
        - containerPort: 8000

